### ISSUE TITLE
Unable to install the environment

### ISSUE THREAD

**Issue by yfhuang7** [AMBehroozi/PINN_workshop_ciroh#1]
I got the error message when I try to install the environment:

PINN_workshop_ciroh % conda env create -f environment.yml 
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0

Solving environment: failed

ResolvePackageNotFound: 
  - libstdcxx-ng==11.2.0=h1234567_1
  - libxml2==2.10.4=hfdd30dd_2
  - mkl-service==2.4.0=py311h5eee18b_1
  - cyrus-sasl==2.1.28=h52b45da_1
  - libunistring==0.9.10=h27cfd23_0
  - jinja2==3.1.3=py311h06a4308_0
  - lz4-c==1.9.4=h6a678d5_1
  - pyzmq==25.1.2=py311h6a678d5_0
  - zstd==1.5.5=hc292b87_2
  - debugpy==1.6.7=py311h6a678d5_0
...

Do I need to pre-install something else?
Note: I'm on MacOS.

Thank you!

**Comment by AMBehroozi** [comment]
Hi,
Did you try on 2i2c JupyterHub?

Alternatively, you only need to install the pytorch package with pip manually.

Cheers
Mehdi



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Yu-Fen Huang ***@***.***>
Sent: Friday, May 24, 2024 6:38:03 PM
To: AMBehroozi/PINN_workshop_ciroh ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AMBehroozi/PINN_workshop_ciroh] Unable to install the environment (Issue #1)


I got the error message when I try to install the environment:

PINN_workshop_ciroh % conda env create -f environment.yml
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0., but conda is ignoring the . and treating it as 1.6.0

Solving environment: failed

ResolvePackageNotFound:

  *   libstdcxx-ng==11.2.0=h1234567_1
  *   libxml2==2.10.4=hfdd30dd_2
  *   mkl-service==2.4.0=py311h5eee18b_1
  *   cyrus-sasl==2.1.28=h52b45da_1
  *   libunistring==0.9.10=h27cfd23_0
  *   jinja2==3.1.3=py311h06a4308_0
  *   lz4-c==1.9.4=h6a678d5_1
  *   pyzmq==25.1.2=py311h6a678d5_0
  *   zstd==1.5.5=hc292b87_2
  *   debugpy==1.6.7=py311h6a678d5_0
...

Do I need to pre-install something else?
Note: I'm on MacOS.

Thank you!

**Comment by yfhuang7** [comment]
Got it! Thank you!
